services:
  stg_keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: stg_postgres_keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "4999:8080"
    depends_on:
      stg_postgres_keycloak:
        condition: service_healthy
    networks:
      - stg_uom_keycloak_network

  stg_postgres_keycloak:
    image: postgres:14.2
    command: postgres -c 'max_connections=200'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: "exit 0"
    ports:
      - "4998:5432"
    networks:
      - stg_uom_keycloak_network
volumes:
  pgdata_stg_keycloak:
networks:
  stg_uom_keycloak_network:
    driver: bridge
