version: '3'

volumes:
  pgdata_stg_keycloak:
networks:
  stg_uom_network:

services:
  stg_keycloak:
    container_name: stg_keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 5999:8080
    networks:
      - stg_uom_network
    environment:
      DB_VENDOR: postgres
      DB_ADDR: stg_postgres_keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      DB_SCHEMA: public
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    depends_on:
      - stg_keycloak_postgres

  stg_keycloak_postgres:
    container_name: stg_keycloak_postgres
    image: postgres
    ports:
      - 5998:5432
    networks:
      - stg_uom_network
    #command: postgres -c 'max_connections=200'
    volumes:
      - pgdata_stg_keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

